version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: test-db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test